name: build-push-cloud

run-name: build-cloud@${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false

  push:
    branches:
      - 'main'
      - 'workspace/**'
    paths:
      - '.github/**'
      - 'scripts/setup/**'

defaults:
  run:
    shell: bash

jobs:
  build-cloud:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      DOCKERFILE_PATH: ./.github/docker/Dockerfile
      BUILD_CONTEXT: .
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into Docker Hub (for Build Cloud)
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx with Docker Build Cloud
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "dishtaweera/smb-ros2-workspace"
          install: true

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          context: git
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: latest=false
          tags: type=ref,event=branch

      - name: Build and push Docker image (multi-arch, via Build Cloud)
        id: docker-build
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.BUILD_CONTEXT }}
          file: ${{ env.DOCKERFILE_PATH }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ always() && github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          connect-timeout-seconds: 5